name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Raptor's documentation!

  - type: dropdown
    id: category
    attributes:
      label: Documentation Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Unclear/confusing explanation
        - Incorrect information
        - Outdated information
        - Example needed
        - Typo/grammar
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: "e.g., README.md, API docs for Kernel, jsr.io page"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing? Be specific.
      placeholder: The documentation doesn't explain... / The example shows... but should show...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Could be clearer if it explained... / Would be helpful to add an example showing...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
